"""add required column to resource_slot

Revision ID: f11ecd5c55cf
Revises: c3218103909a
Create Date: 2026-06-07 11:20:05.400061

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f11ecd5c55cf"
down_revision = "c3218103909a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource_slot",
        sa.Column("required", sa.Boolean(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource_slot", "required")
    # ### end Alembic commands ###
